<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Include="wwwroot\assets\js\custom\account\api-keys\api-keys.js" />
    <None Include="wwwroot\assets\js\custom\account\billing\general.js" />
    <None Include="wwwroot\assets\js\custom\account\referrals\referral-program.js" />
    <None Include="wwwroot\assets\js\custom\account\security\license-usage.js" />
    <None Include="wwwroot\assets\js\custom\account\security\security-summary.js" />
    <None Include="wwwroot\assets\js\custom\account\settings\deactivate-account.js" />
    <None Include="wwwroot\assets\js\custom\account\settings\profile-details.js" />
    <None Include="wwwroot\assets\js\custom\account\settings\signin-methods.js" />
    <None Include="wwwroot\assets\js\custom\apps\calendar\calendar.js" />
    <None Include="wwwroot\assets\js\custom\apps\chat\chat.js" />
    <None Include="wwwroot\assets\js\custom\apps\contacts\edit-contact.js" />
    <None Include="wwwroot\assets\js\custom\apps\contacts\view-contact.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\add.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\list\export.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\list\list.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\update.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\add-payment.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\adjust-balance.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\invoices.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\payment-method.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\payment-table.js" />
    <None Include="wwwroot\assets\js\custom\apps\customers\view\statement.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\catalog\categories.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\catalog\products.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\catalog\save-category.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\catalog\save-product.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\add-address.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\add-auth-app.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\add-one-time-password.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\transaction-history.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\update-address.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\update-password.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\update-phone.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\details\update-profile.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\listing\add.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\listing\export.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\customers\listing\listing.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\reports\customer-orders\customer-orders.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\reports\returns\returns.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\reports\sales\sales.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\reports\shipping\shipping.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\reports\views\views.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\sales\listing.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\sales\save-order.js" />
    <None Include="wwwroot\assets\js\custom\apps\ecommerce\settings\settings.js" />
    <None Include="wwwroot\assets\js\custom\apps\file-manager\list.js" />
    <None Include="wwwroot\assets\js\custom\apps\file-manager\settings.js" />
    <None Include="wwwroot\assets\js\custom\apps\inbox\compose.js" />
    <None Include="wwwroot\assets\js\custom\apps\inbox\listing.js" />
    <None Include="wwwroot\assets\js\custom\apps\inbox\reply.js" />
    <None Include="wwwroot\assets\js\custom\apps\invoices\create.js" />
    <None Include="wwwroot\assets\js\custom\apps\projects\list\list.js" />
    <None Include="wwwroot\assets\js\custom\apps\projects\project\project.js" />
    <None Include="wwwroot\assets\js\custom\apps\projects\settings\settings.js" />
    <None Include="wwwroot\assets\js\custom\apps\projects\targets\targets.js" />
    <None Include="wwwroot\assets\js\custom\apps\projects\users\users.js" />
    <None Include="wwwroot\assets\js\custom\apps\subscriptions\add\advanced.js" />
    <None Include="wwwroot\assets\js\custom\apps\subscriptions\add\customer-select.js" />
    <None Include="wwwroot\assets\js\custom\apps\subscriptions\add\products.js" />
    <None Include="wwwroot\assets\js\custom\apps\subscriptions\list\export.js" />
    <None Include="wwwroot\assets\js\custom\apps\subscriptions\list\list.js" />
    <None Include="wwwroot\assets\js\custom\apps\support-center\general.js" />
    <None Include="wwwroot\assets\js\custom\apps\support-center\tickets\create.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\permissions\add-permission.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\permissions\list.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\permissions\update-permission.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\roles\list\add.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\roles\list\update-role.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\roles\view\update-role.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\roles\view\view.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\list\add.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\list\export-users.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\list\table.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\add-auth-app.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\add-one-time-password.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\add-schedule.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\add-task.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\update-details.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\update-email.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\update-password.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\update-role.js" />
    <None Include="wwwroot\assets\js\custom\apps\user-management\users\view\view.js" />
    <None Include="wwwroot\assets\js\custom\authentication\reset-password\new-password.js" />
    <None Include="wwwroot\assets\js\custom\authentication\reset-password\reset-password.js" />
    <None Include="wwwroot\assets\js\custom\authentication\sign-in\general.js" />
    <None Include="wwwroot\assets\js\custom\authentication\sign-in\i18n.js" />
    <None Include="wwwroot\assets\js\custom\authentication\sign-in\two-factor.js" />
    <None Include="wwwroot\assets\js\custom\authentication\sign-up\coming-soon.js" />
    <None Include="wwwroot\assets\js\custom\authentication\sign-up\general.js" />
    <None Include="wwwroot\assets\js\custom\landing.js" />
    <None Include="wwwroot\assets\js\custom\layout-builder\layout-builder.js" />
    <None Include="wwwroot\assets\js\custom\pages\careers\apply.js" />
    <None Include="wwwroot\assets\js\custom\pages\general\contact.js" />
    <None Include="wwwroot\assets\js\custom\pages\general\pos.js" />
    <None Include="wwwroot\assets\js\custom\pages\pricing\general.js" />
    <None Include="wwwroot\assets\js\custom\pages\social\feeds.js" />
    <None Include="wwwroot\assets\js\custom\pages\user-profile\general.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\bidding.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-account.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-api-key.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-app.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-campaign.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\budget.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\complete.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\files.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\main.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\settings.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\targets.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\team.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\create-project\type.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\new-address.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\new-card.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\new-target.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\offer-a-deal\complete.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\offer-a-deal\details.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\offer-a-deal\finance.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\offer-a-deal\main.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\offer-a-deal\type.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\select-location.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\share-earn.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\top-up-wallet.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\two-factor-authentication.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\upgrade-plan.js" />
    <None Include="wwwroot\assets\js\custom\utilities\modals\users-search.js" />
    <None Include="wwwroot\assets\js\custom\utilities\search\horizontal.js" />
    <None Include="wwwroot\assets\js\custom\widgets.js" />
    <None Include="wwwroot\assets\js\scripts.bundle.js" />
    <None Include="wwwroot\assets\js\widgets.bundle.js" />
    <None Include="wwwroot\assets\media\email\icon-dribbble.svg" />
    <None Include="wwwroot\assets\media\email\icon-facebook.svg" />
    <None Include="wwwroot\assets\media\email\icon-linkedin.svg" />
    <None Include="wwwroot\assets\media\email\icon-polygon.svg" />
    <None Include="wwwroot\assets\media\email\icon-positive-vote-1.svg" />
    <None Include="wwwroot\assets\media\email\icon-positive-vote-2.svg" />
    <None Include="wwwroot\assets\media\email\icon-positive-vote-3.svg" />
    <None Include="wwwroot\assets\media\email\icon-positive-vote-4.svg" />
    <None Include="wwwroot\assets\media\email\icon-twitter.svg" />
    <None Include="wwwroot\assets\media\email\logo-1.svg" />
    <None Include="wwwroot\assets\media\email\logo-2.svg" />
    <None Include="wwwroot\assets\media\flags\australia.svg" />
    <None Include="wwwroot\assets\media\flags\brazil.svg" />
    <None Include="wwwroot\assets\media\flags\france.svg" />
    <None Include="wwwroot\assets\media\flags\germany.svg" />
    <None Include="wwwroot\assets\media\flags\india.svg" />
    <None Include="wwwroot\assets\media\flags\japan.svg" />
    <None Include="wwwroot\assets\media\flags\spain.svg" />
    <None Include="wwwroot\assets\media\flags\sweden.svg" />
    <None Include="wwwroot\assets\media\flags\turkey.svg" />
    <None Include="wwwroot\assets\media\flags\united-kingdom.svg" />
    <None Include="wwwroot\assets\media\flags\united-states.svg" />
    <None Include="wwwroot\assets\media\logos\custom-2.svg" />
    <None Include="wwwroot\assets\media\logos\custom-3.svg" />
    <None Include="wwwroot\assets\media\logos\default-dark.svg" />
    <None Include="wwwroot\assets\media\logos\default.svg" />
    <None Include="wwwroot\assets\media\logos\demo32-small.svg" />
    <None Include="wwwroot\assets\media\logos\demo32.svg" />
    <None Include="wwwroot\assets\media\logos\landing-dark.svg" />
    <None Include="wwwroot\assets\media\logos\landing.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\001-boy.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\004-boy-1.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\006-girl-3.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\014-girl-7.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\018-girl-9.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\020-girl-11.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\029-boy-11.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\043-boy-18.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\047-girl-25.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\blank-dark.svg" />
    <None Include="wwwroot\assets\media\svg\avatars\blank.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\amazon-dark.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\amazon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\angular-icon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\aon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\apple-black-dark.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\apple-black.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\aspnetzero.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\atica.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\aven.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\balloon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\beats-electronics.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\bebo.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\behance.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\bootstrap5.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\bp-2.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\code-lab.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\disqus.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\dribbble-icon-1.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\duolingo.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\facebook-3.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\facebook-4.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\figma-1.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\fox-hub.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\fujifilm.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\github.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\google-icon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\hp-3.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\instagram-2-1.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\invision.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\kanba.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\kickstarter.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\kpmg.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\laravel-2.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\leaf.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\linkedin-1.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\linkedin-2.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\lloyds-of-london-logo.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\nasa.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\pinterest-p.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\plurk.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\reddit.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\sentry-3.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\slack-icon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\spotify.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\spring-3.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\telegram-2.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\telegram.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\tower.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\treva.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\truman.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\tvit.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\twitch.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\twitter-2.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\twitter.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\typescript-1.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\vimeo.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\vodafone.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\volicity-9.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\vue-9.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\xing-icon.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\youtube-3.svg" />
    <None Include="wwwroot\assets\media\svg\brand-logos\youtube-play.svg" />
    <None Include="wwwroot\assets\media\svg\card-logos\american-express.svg" />
    <None Include="wwwroot\assets\media\svg\card-logos\mastercard.svg" />
    <None Include="wwwroot\assets\media\svg\card-logos\visa.svg" />
    <None Include="wwwroot\assets\media\svg\coins\binance.svg" />
    <None Include="wwwroot\assets\media\svg\coins\bitcoin.svg" />
    <None Include="wwwroot\assets\media\svg\coins\chainlink.svg" />
    <None Include="wwwroot\assets\media\svg\coins\coin.svg" />
    <None Include="wwwroot\assets\media\svg\coins\ethereum.svg" />
    <None Include="wwwroot\assets\media\svg\coins\filecoin.svg" />
    <None Include="wwwroot\assets\media\svg\files\ai-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\ai.svg" />
    <None Include="wwwroot\assets\media\svg\files\blank-image-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\blank-image.svg" />
    <None Include="wwwroot\assets\media\svg\files\css-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\css.svg" />
    <None Include="wwwroot\assets\media\svg\files\doc-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\doc.svg" />
    <None Include="wwwroot\assets\media\svg\files\folder-document-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\folder-document.svg" />
    <None Include="wwwroot\assets\media\svg\files\pdf-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\pdf.svg" />
    <None Include="wwwroot\assets\media\svg\files\sql-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\sql.svg" />
    <None Include="wwwroot\assets\media\svg\files\tif-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\tif.svg" />
    <None Include="wwwroot\assets\media\svg\files\upload.svg" />
    <None Include="wwwroot\assets\media\svg\files\xml-dark.svg" />
    <None Include="wwwroot\assets\media\svg\files\xml.svg" />
    <None Include="wwwroot\assets\media\svg\food-icons\cheeseburger.svg" />
    <None Include="wwwroot\assets\media\svg\food-icons\cheesecake.svg" />
    <None Include="wwwroot\assets\media\svg\food-icons\coffee.svg" />
    <None Include="wwwroot\assets\media\svg\food-icons\salad.svg" />
    <None Include="wwwroot\assets\media\svg\food-icons\spaghetti.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\1-dark.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\1.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\2-dark.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\2.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\3-dark.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\3.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\5.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\6.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\easy\7.svg" />
    <None Include="wwwroot\assets\media\svg\illustrations\landing.svg" />
    <None Include="wwwroot\assets\media\svg\misc\infography.svg" />
    <None Include="wwwroot\assets\media\svg\misc\layer.svg" />
    <None Include="wwwroot\assets\media\svg\misc\octagon.svg" />
    <None Include="wwwroot\assets\media\svg\misc\smartphone-2-dark.svg" />
    <None Include="wwwroot\assets\media\svg\misc\smartphone-2.svg" />
    <None Include="wwwroot\assets\media\svg\misc\video-play.svg" />
    <None Include="wwwroot\assets\media\svg\products-categories\gaming.svg" />
    <None Include="wwwroot\assets\media\svg\products-categories\gloves.svg" />
    <None Include="wwwroot\assets\media\svg\products-categories\shoes.svg" />
    <None Include="wwwroot\assets\media\svg\products-categories\t-shirt.svg" />
    <None Include="wwwroot\assets\media\svg\products-categories\watch.svg" />
    <None Include="wwwroot\assets\media\svg\shapes\bitcoin.svg" />
    <None Include="wwwroot\assets\media\svg\shapes\dogecoin.svg" />
    <None Include="wwwroot\assets\media\svg\shapes\ethereum.svg" />
    <None Include="wwwroot\assets\media\svg\shapes\wave-bg-purple.svg" />
    <None Include="wwwroot\assets\media\svg\shapes\wave-bg-red.svg" />
    <None Include="wwwroot\assets\media\svg\social-logos\facebook.svg" />
    <None Include="wwwroot\assets\media\svg\social-logos\google.svg" />
    <None Include="wwwroot\assets\media\svg\social-logos\twitter.svg" />
    <None Include="wwwroot\assets\plugins\custom\datatables\datatables.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\formrepeater\formrepeater.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\fslightbox\fslightbox.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\fullcalendar\fullcalendar.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\leaflet\leaflet.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\prismjs\prismjs.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\typedjs\typedjs.bundle.js" />
    <None Include="wwwroot\assets\plugins\custom\vis-timeline\vis-timeline.bundle.js" />
    <None Include="wwwroot\assets\plugins\global\fonts\%40fortawesome\fa-brands-400.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\%40fortawesome\fa-regular-400.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\%40fortawesome\fa-solid-900.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\%40fortawesome\fa-v4compatibility.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\bootstrap-icons\bootstrap-icons.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\keenicons\keenicons-duotone.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\keenicons\keenicons-outline.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\keenicons\keenicons-solid.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-brands-400.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-brands-400.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-regular-400.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-regular-400.woff2" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-solid-900.svg" />
    <None Include="wwwroot\assets\plugins\global\fonts\line-awesome\la-solid-900.woff2" />
    <None Include="wwwroot\assets\plugins\global\plugins.bundle.js" />
    <None Include="wwwroot\gtag\js" />
    <None Include="wwwroot\gtag\js-1" />
    <None Include="wwwroot\gtag\js-2" />
    <None Include="wwwroot\gtag\js-3" />
    <None Include="wwwroot\gtag\js-4" />
    <None Include="wwwroot\gtag\js-5" />
    <None Include="wwwroot\lib\5\geodata\continentsLow-1.js" />
    <None Include="wwwroot\lib\5\geodata\continentsLow-2.js" />
    <None Include="wwwroot\lib\5\geodata\continentsLow-3.js" />
    <None Include="wwwroot\lib\5\geodata\continentsLow-4.js" />
    <None Include="wwwroot\lib\5\geodata\continentsLow-5.js" />
    <None Include="wwwroot\lib\5\geodata\continentsLow.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow-1.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow-2.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow-3.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow-4.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow-5.js" />
    <None Include="wwwroot\lib\5\geodata\usaLow.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow-1.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow-2.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow-3.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow-4.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow-5.js" />
    <None Include="wwwroot\lib\5\geodata\worldLow.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow-1.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow-2.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow-3.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow-4.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow-5.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZoneAreasLow.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow-1.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow-2.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow-3.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow-4.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow-5.js" />
    <None Include="wwwroot\lib\5\geodata\worldTimeZonesLow.js" />
    <None Include="wwwroot\lib\5\index-1.js" />
    <None Include="wwwroot\lib\5\index-2.js" />
    <None Include="wwwroot\lib\5\index-3.js" />
    <None Include="wwwroot\lib\5\index-4.js" />
    <None Include="wwwroot\lib\5\index-5.js" />
    <None Include="wwwroot\lib\5\index.js" />
    <None Include="wwwroot\lib\5\map-1.js" />
    <None Include="wwwroot\lib\5\map-2.js" />
    <None Include="wwwroot\lib\5\map-3.js" />
    <None Include="wwwroot\lib\5\map-4.js" />
    <None Include="wwwroot\lib\5\map-5.js" />
    <None Include="wwwroot\lib\5\map.js" />
    <None Include="wwwroot\lib\5\percent-1.js" />
    <None Include="wwwroot\lib\5\percent-2.js" />
    <None Include="wwwroot\lib\5\percent-3.js" />
    <None Include="wwwroot\lib\5\percent-4.js" />
    <None Include="wwwroot\lib\5\percent-5.js" />
    <None Include="wwwroot\lib\5\percent.js" />
    <None Include="wwwroot\lib\5\radar-1.js" />
    <None Include="wwwroot\lib\5\radar-2.js" />
    <None Include="wwwroot\lib\5\radar-3.js" />
    <None Include="wwwroot\lib\5\radar-4.js" />
    <None Include="wwwroot\lib\5\radar-5.js" />
    <None Include="wwwroot\lib\5\radar.js" />
    <None Include="wwwroot\lib\5\themes\Animated-1.js" />
    <None Include="wwwroot\lib\5\themes\Animated-2.js" />
    <None Include="wwwroot\lib\5\themes\Animated-3.js" />
    <None Include="wwwroot\lib\5\themes\Animated-4.js" />
    <None Include="wwwroot\lib\5\themes\Animated-5.js" />
    <None Include="wwwroot\lib\5\themes\Animated.js" />
    <None Include="wwwroot\lib\5\xy-1.js" />
    <None Include="wwwroot\lib\5\xy-2.js" />
    <None Include="wwwroot\lib\5\xy-3.js" />
    <None Include="wwwroot\lib\5\xy-4.js" />
    <None Include="wwwroot\lib\5\xy-5.js" />
    <None Include="wwwroot\lib\5\xy.js" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <None Include="wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
    <None Include="wwwroot\lib\bootstrap\LICENSE" />
    <None Include="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js" />
    <None Include="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\additional-methods.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
    <None Include="wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
    <None Include="wwwroot\lib\jquery-validation\LICENSE.md" />
    <None Include="wwwroot\lib\jquery\dist\jquery.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.min.js" />
    <None Include="wwwroot\lib\jquery\dist\jquery.min.map" />
    <None Include="wwwroot\Resimler\arac.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.72" />
    <PackageReference Include="leaflet" Version="0.7.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.20">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="7.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataBaseLayer\DataBaseLayer.csproj" />
    <ProjectReference Include="..\EntityLayer\EntityLayer.csproj" />
  </ItemGroup>

</Project>
